# Register
# ../src/controllers/auth.controller.ts
POST http://localhost:5501/api/auth/register
Accept: application/json
X-Platform: yu2ahel
Content-Type: application/json

{
  "email": "werwerwer12@gmail.com",
  "userName": "werwerwe113",
  "password": "123456",
  "fullName": "Hazem nabil Safwat",
  "userProfileData": {
    "additionalData": {
      "Children": [
        {
          "name": "yaseen",
          "age": "20"
        },
        {
          "name": "abdo",
          "age": "18"
        }
      ]
    }
  }
}


###

# Login
# ../src/controllers/auth.controller.ts
# userName can be username or email
#  "username": "striker.h+73@gmail.com" (Email)
#  "username": "striker73", (UserName)
POST http://localhost:5501/api/auth/login
Accept: application/json
X-Platform: yu2ahel
Content-Type: application/json

{
  "username": "striker73",
  "password": "123456"
}

###




