GET http://localhost:5501/
Accept: application/json


###

POST http://localhost:5501/api/register
Accept: application/json
X-Platform: yu2ahel
Content-Type: application/json

{
  "email": "striker.h@gmail.com",
  "password": "123456",
  "username": "striker.h@gmail.com"
}


###

POST http://localhost:5501/api/login
Accept: application/json
X-Platform: yu2ahel
Content-Type: application/json

{
  "email": "striker.h@gmail.com",
  "password": "123456",
  "username": "striker.h@gmail.com"
}
